<?php

/**
 * @file
 * Module to add catalog search feature to citations
 */

/**
 * Page callback: Islandora catalog search settings
 *
 * @see islandora_catalog_search_menu()
 */
function islandora_catalog_search_form($form, &$form_state) {
  // checkbox options
  $form['islandora_catalog_search_options'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Options'),
    '#options' => array(
      'new_window' => t('Open link in new window'),
      'use_image' => t('Use image for link'),
    ),
    '#default_value' => variable_get('islandora_catalog_search_options', ''),
  );

  // catalog url
  $form['library_catalog_search'] += _islandora_scholar_add_variable('islandora_scholar_library_catalog_search_URL', 'https://american.summon.serialssolutions.com', array(
    '#type' => 'textfield',
    '#title' => t('Library Catalog Location'),
    '#description' => t('The search URL for your library\'s discovery layer.'),
    '#states' => array(
      'visible' => array(
        ':input[name="islandora_scholar_library_catalog_search_enabled"]' => array('checked' => TRUE),
      ),
    ),
  ));
  // http parameters
$form['library_catalog_search'] += _islandora_scholar_add_variable('islandora_scholar_library_catalog_search_params', '/search?s.q=', array(
    '#type' => 'textfield',
    '#title' => t('Library Search Parameters'),
    '#description' => t('The search parameters for your library\'s discovery layer. Default configuration for Summon discovery layer is shown.'),
    '#states' => array(
      'visible' => array(
        ':input[name="islandora_scholar_library_catalog_search_enabled"]' => array('checked' => TRUE),
      ),
    ),
  ));
$form['library_catalog_search'] += _islandora_scholar_add_variable('islandora_scholar_library_catalog_primary_search_xpath', "//mods:identifier[@type=\"doi\"]", array(
    '#type' => 'textfield',
    '#title' => t('Library Catalog Primary Search XPath'),
    '#description' => t('The primary xpath you want to use to search.'),
    '#states' => array(
      'visible' => array(
        ':input[name="islandora_scholar_library_catalog_search_enabled"]' => array('checked' => TRUE),
      ),
    ),
  ));
  $form['library_catalog_search'] += _islandora_scholar_add_variable('islandora_scholar_library_catalog_default_search_xpath', "//mods:title", array(
    '#type' => 'textfield',
    '#title' => t('Library Catalog Default Search XPath'),
    '#description' => t('The default xpath you want to use to search'),
    '#states' => array(
      'visible' => array(
        ':input[name="islandora_scholar_library_catalog_search_enabled"]' => array('checked' => TRUE),
      ),
    ),
  ));
  // upload image
  $form['islandora_catalog_search_link_image'] = array(
    '#type' => 'managed_file',
    '#name' => 'link_image',
    '#title' => t('Link Image'),
    '#default_value' => variable_get('islandora_catalog_search_link_image', ''),
    '#description' => t("Use this image as the link to your catalog"),
    '#upload_location' => 'public://catalog_link_image',
  );

  // image size
  $form['islandora_catalog_search_link_image_width'] = array(
    '#type' => 'textfield',
    '#title' => t('Image Width'),
    '#default_value' => variable_get('islandora_catalog_search_link_image_width', '150'),
    '#size' => 100,
    '#description' => t('The width of the link image'),
  );
  $form['islandora_catalog_search_link_image_height'] = array(
    '#type' => 'textfield',
    '#title' => t('Image Height'),
    '#default_value' => variable_get('islandora_catalog_search_link_image_height', '50'),
    '#size' => 100,
    '#description' => t('The height of the link image'),
  );

  // link text
  $form['islandora_catalog_search_link_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Link Text'),
    '#default_value' => variable_get('islandora_catalog_search_link_text', 'Check our catalog'),
    '#size' => 100,
    '#description' => t('The Text to display for the link to the catalog if not using an image'),
  );

  // submit handler to save link image
  $form['#submit'][] = 'islandora_catalog_search_form_submit';

  return system_settings_form($form);
}


/*
 * Additional submit handler for making the link image file permanent
 */
function islandora_catalog_search_form_submit($form, &$form_state) {
  $file = $form['islandora_catalog_search_link_image']['#file'];
  if (is_object($file)) {
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
    // prevent 'file not referenced' warning
    file_usage_add($file, 'islandora_catalog_link', 'node', 1);
  }
}


/**
 * Validate the size of the image specified in the admin form
 */
function islandora_catalog_search_form_validate($form, &$form_state) {
  $width = $form_state['values']['islandora_catalog_search_link_image_width'];
  $height = $form_state['values']['islandora_catalog_search_link_image_height'];

  if (!is_numeric($width)) {
    form_set_error('islandora_catalog_search_link_image_width', t('You must enter an integer for the image width.'));
  }

  elseif (!is_numeric($height)) {
    form_set_error('islandora_catalog_search_link_image_height', t('You must enter an integer for the image height.'));
  }

  elseif ($width <= 0) {
    form_set_error('islandora_catalog_search_link_image_width', t('Image width must be positive.'));
  }

  elseif ($height <= 0) {
    form_set_error('islandora_catalog_search_link_image_height', t('Image height must be positive.'));
  }
}


/**
 * Implements hook_menu().
 */
function islandora_catalog_search_menu() {
  $items = array();

  $items['admin/islandora/islandora_catalog_search'] = array(
    'title' => 'Islandora Catalog Search',
    'description' => 'Configuration for Islandora Catalog Search module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_catalog_search_form'),
    'access arguments' => array('manage islandora catalog search'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
/**
 * Places catalog search links on pages().
 */
if (variable_get('islandora_scholar_library_catalog_search_enabled', FALSE)) {
      // Library Catalog Search.
      $mods_xml = simplexml_load_string($object['MODS']->content);
      $mods_xml->registerXPathNamespace('mods', 'http://www.loc.gov/mods/v3');
      // Search for library search URL
      $search_url = NULL;
      $search_url = variable_get('islandora_scholar_library_catalog_search_URL', 'https://american.summon.serialssolutions.com');
      // Search for library search parameters
      $search_params = NULL;
      $search_params = variable_get('islandora_scholar_library_catalog_search_params', '/search?s.q=');
      // Search for primary search term (usually DOI).
      $search_term = NULL;
      $primary_search = $mods_xml->xpath("" . variable_get('islandora_scholar_library_catalog_primary_search_xpath', '//mods:identifier[@type="doi"]'));
      if ($primary_search) {
        $search_term = (string) reset($primary_search);
      }
      if (!$search_term) {
        // Search for default search term (usually title).
        $default_search = $mods_xml->xpath("" . variable_get('islandora_scholar_library_catalog_default_search_xpath', '//mods:title'));
        $search_term = (string) reset($default_search);
      }
      if (!$search_term) {
        $search_term = $object->label;
      }

      $display['library_catalog_search'] = array(
        '#type' => 'item',
        '#markup' => l(t('Search for this publication in your library discovery service'), "$search_url$search_params\"$search_term\""),
        '#weight' => 0,
      );
    }
  }
  else {
    $display['citation']['#markup'] = t('Unable to load MODS.');
  }

/**
 * Implements hook_permission
 */
function islandora_catalog_search_permission() {
  return array(
    'manage islandora catalog search' => array(
      'title' => t('Manage Islandora Catalog Search'),
      'description' => t('Perform admin tasks for the Islandora Catalog Search Module'),
    )
  );
}
